In [1]:
import random

In [2]:
k = random.random()
print(k)

0.4765245137440719


In [3]:
k = random.randint(1,10)
print(k)

5


In [4]:
k = random.uniform(1,10)
print(k)

5.738115736066062


In [5]:
k = random.randrange(1,10)       # here 10 will be excluded
print(k)                       

3


In [6]:
k = random.normalvariate(0,1)
print(k)

1.202525060893178


In [7]:
k = random.choice(list('asdfghklzxcvbnmwertyuiop')) # chooses a random element from the sequence
print(k)

b


In [8]:
k = random.sample(list('qwetyuiopasdfghjklxcvbnm'), 4) # choose k element from the sequence
print(k)

['q', 'p', 'l', 'k']


In [9]:
k = random.choices(list('qwertyuiopsdfghjklxcvbnm'), k=4)
print(k)

['g', 'p', 'x', 'n']


In [10]:
a= list('asdfghjklzxcvbnm')
random.shuffle(a)
print(a)

['n', 'h', 'x', 'd', 'g', 'v', 'f', 'k', 'a', 's', 'l', 'z', 'm', 'c', 'b', 'j']


## the seed generator

In [11]:
print('the 1 seeding begins..\n')

random.seed(1)
print(random.random())
print(random.randint(1,10),'\n')

print('the 2 seeding bengins..\n')

random.seed(2)
print(random.random())
print(random.randint(1,10))

the 1 seeding begins..

0.13436424411240122
2 

the 2 seeding bengins..

0.9560342718892494
1


## the secret module

In [12]:
import secrets

In [20]:
print(secrets.randbelow(1000000000))
print(secrets.randbits(5))
print(secrets.choice(list('asdghjklzxcvbnm')))

63269651
8
n


## random numbers with numpy

In [21]:
import numpy as np

In [27]:
np.random.seed(1)
print(np.random.rand(10))

np.random.seed(1)
print(np.random.rand(10))

[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]
[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01
 1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01
 3.96767474e-01 5.38816734e-01]


In [31]:
print(np.random.randint(1,10, (5,5)))

[[6 3 5 3 5]
 [8 8 2 8 1]
 [7 8 7 2 1]
 [2 9 9 4 9]
 [8 4 7 6 2]]


In [32]:
print(np.random.randn(9))

[ 1.91382039  0.33079713  1.14194252 -1.12959516 -0.85005238  0.96082
 -0.21741818  0.15851488  0.87341823]


In [36]:
k = np.array([[6,3,5,3,5], [8,8,2,8,1], [7,8,7,2,1], [2,9,9,4,9], [8,4,7,6,2]])
np.random.shuffle(k)
print(k)

[[6 3 5 3 5]
 [2 9 9 4 9]
 [8 8 2 8 1]
 [8 4 7 6 2]
 [7 8 7 2 1]]
